src/sugar3/bundle/activitybundle.py
When we ported sugar to Gtk3 we removed the support of the fields
exec and service_name due they were deprecated for a long time [1].
But this is still a problem in deployments, and we already added
compatibility for the service_name field.
Here [3] there is a long thred were we discussed this issue.
[1] ae85dd62d42a7d5bea76aec3b941ce35ccc61bf4
[2] 32f97b48c31f60f306854753a3df734f63b798fc
[3] http://lists.sugarlabs.org/archive/sugar-devel/2013-October/045404.html
=> Don't break activity startup if .info have 'class' instead of 'exec'

src/sugar3/graphics/icon.py
These are simple optimizations, are the first part of the treeview optimization described 
in the feature [1].
* avoid execute slow methods while the icon is rendered
* remove a unneeded operation
* cache size offset calculation
Are isolated from other changes and do not change the API.
[1] http://wiki.sugarlabs.org/go/Features/Optimize_TreeViews
=> Cell renderer icon optimizations

src/sugar3/graphics/palettewindow.py
Popdown a palette window in response to escape key.
Restores the use of the keyboard for interaction with Sugar after startup, without having to use mouse to dismiss the buddy icon menu.
Tested on XO-4 with Sugar 0.105.1.
=> Add escape key to palette windows

src/sugar3/activity/bundlebuilder.py
Historically, distro packagers have been using bunblebuilder, via
"setup.py install", to populate packages directories and files.
The install procedure uses ActivityBundle.install_mime_type to install
custom mime types, by creating symlinks and updating the system mime
types database via the update-mime-database tool.
When ActivityBundle.install_mime_type is executed during packages
creation, the symlinks end-up broken in the final package and the use
of update-mime-database populates the final packages with a new copy
of the database files which could clash with the system copy.
This patch adds a new option, called --skip-install-mime to "setup.py
install" to skip the execution of ActivityBundle.install_mime_type and
avoid the issues mentioned above.
Activity packagers should use this …
=> Add skip-install-mime option to bundlebuilder

bin/sugar-activity-web
Gears activity on Ubuntu with Sugar 0.105.1 shows this in logs:
```
/usr/bin/sugar-activity-web: 20: [: unexpected operator
```
Cause is bash-specific coding in script.
=> sugar-activity-web: remove bash specific code

src/sugar3/graphics/palette.py
When a activity have a title very long without spaces,
the text can't be wraped with the default wrap mode (WORD)
Use WRAP_CHAR to solve this issue.
=> Secondary text on palettes should respect the max width - Fixes #4862

src/sugar3/graphics/radiotoolbutton.py
When we use set_icon_widget(), GtkToolButton set a private property
contents_invalid = TRUE [1], and gtk_tool_button_construct_content [2]
is called. Then if the label widget not exist, a GtkLabel is added.
This is a problem for us, by example in the Clipboard buttons in the frame.
By adding a empty Gtk.Box instead of a label, we avoid the label creation.
But as this is a internal implementation of Gtk, can change in the future,
in fact the issue is not visible with Gtk < 3.16
This patch is based in a pr sent by Sam Parkinson
[1] https://github.com/GNOME/gtk/blob/master/gtk/gtktoolbutton.c#L1415
[2] https://github.com/GNOME/gtk/blob/master/gtk/gtktoolbutton.c#L357
=> Don't add a label on RadioToolButton when set icon_widget - Fixes #4875

src/sugar3/graphics/palettemenu.py
Ticket URL <http://bugs.sugarlabs.org/ticket/4863>
@Quozl wrote a very good ticket which serves as a good description:
The industry convention for mouse driven menu options is for them to be activated when two conditions are met:
* a button down event occurs with the pointer inside the option, and;
* a button up event occurs with the pointer inside the option. 
The latter condition is not being checked in the Sugar menus.
Reproducer: right-click on the buddy menu, put the pointer over the My Settings option, press down on the button, move the pointer out of the menu, release the button.
Expected result: menu is dismissed.
Observed result: menu is dismissed, and the My Settings option is activated.
=> Only activate menu items if the mouse releases in them - fixes #4863

src/sugar3/graphics/icon.py, src/sugar3/graphics/palettewindow.py
These patches complement the fix of bug http://bugs.sugarlabs.org/ticket/4863 taking care of the events on the EventIcons and their palettes.
A new event 'activate' is added for consistency with PaletteMenuItem.
Changes in Sugar are needed to use this event, but do not brek compatibility.
=> Check icon release pos

src/sugar3/graphics/palettewindow.py
The mouse detector have a variable to store the id for the timeout.
The stop() method check if the id is null but do not set the id to null
after remove the GObject timeout, then try to remove the timeout multiple times.
The efect can be seen if a user move the mouse slowly over the icons
in the Sugar home, in shell.log we see many lines like:
sugar3/graphics/palettewindow.py:443: Warning: Source ID 2464 was not found
when attempting to remove it
=> MouseDetector timeout_id need reset

src/sugar3/activity/bundlebuilder.py
When is used to clone a activity from sugar,
the options parameter is set to None.
The other uses of no_fail have False as default value
but this case was missing.
The effect of this error is that a .xo is not created in the Journal,
when the user select 'Duplicate' in the View Source window.
=> Check if parameter 'options' is None in cmd_dist_xo

src/sugar3/graphics/icon.py
With the introduction of 'activate' signal on [1], and the use of that
signal in Sugar Home, we introduced a bug, now, pressing the secondary button
starts the activity instead of open the palette.
This patch solves the issue checking the putton pressed before send the signal.
[1] a19cf9ed2787f9db492fcac4505d5bc52dbaf3a0
=> EventIcon: only trigger 'activate' signal on principal button click

src/sugar3/graphics/palettewindow.py
To solve ticket #4673, we calculate the palette size using the size
of all the widgets [2]. That solves the problem on Palettes based on
_PaletteMenuWidget but on _PaletteWindowWidget produce a wrong value
when the secondary_label is not null, and as a consequence
the palette position is wrong.
The solution is do the calculation only for _PaletteMenuWidget based
palettes.
[1] https://bugs.sugarlabs.org/ticket/4673
[2] b9d6b628a98fc17f5e92a344450b6336f1a2b2ce
=> Do not calculate palette height on PaletteWindowWidget - Fixes #4792

src/sugar3/datastore/datastore.py
Right now is not possible do "from sugar3.datastore import datastore"
outside of GLib loop, because the import try to connect to a DBus signal,
and throw a exception.
That was not a problem in Sugar, because we always have a Glib loop
on all our activities, but is a problem when we want import the classes
to generate docs with pydoc. Many other classes import datastore,
then this is a blocker.
This patch removes the initialization when imported,
will be done when needed.
=> Init the datastore on demand

src/sugar3/activity/activity.py
Replaces https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/253.
Add links to read_file() and write_file(), but ot to __init__()  because is not documented.
Added __init() in the example code to make it more clear.
Also, formatted better the test at the start describing the module.
=> Improve documentation on activity module

src/sugar3/activity/activity.py
As the ticket describe, create a object in the Journal
is no longer optional. The change do not break activities,
because the optional parameter is not removed, just ignored.
=> Deprecate create_jobject parameter on activity.py - Fixes #3450

src/sugar3/graphics/alert.py
For an object of class ```TimeoutAlert```, an OK response occurs on timeout, even if user has clicked a button.
Remove the timeout when the user clicks a button.
A new method ```_response``` is added which overrides the parent method.
=> remove GSource used by TimeoutAlert

src/sugar3/logger.py
When disk is full, Sugar will not start, because the backup log directory cannot be created.
X session logs in tmpfs show this exception:
```
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/lib/python2.7/site-packages/jarabe/main.py", line 20, in <module>
logger.cleanup()
File "/usr/lib/python2.7/site-packages/sugar3/logger.py", line 113, in cleanup
os.mkdir(backup_dir)
OSError: [Errno 28] No space left on device:
'/home/user/.sugar/default/logs/1448258018'
```
Fix is to ignore the exception.
We've been here before!  Was previously fixed in 2010:
- https://github.com/sugarlabs/sugar/commit/4cde481
- …
=> allow start on full disk

src/sugar3/graphics/colorbutton.py, src/sugar3/graphics/menuitem.py, src/sugar3/graphics/toggletoolbutton.py, src/sugar3/graphics/toolbutton.py
This warning is frequently seen in logs but is not that important to warrant being a warning.
=> demote warning to debug for sugar_accel_group

src/sugar3/graphics/colorbutton.py
icon_size was changed to pixel_size, yet references remained, causing
extra log data.
=> Fix remaining icon_size references

src/sugar3/activity/activityfactory.py
Sugar depended on Rainbow for clearing the activity instance/ and tmp/ directories.  But Rainbow is no longer used downstream.
- remove support for Rainbow,
- avoid race when creating directories; don't check they exist before we create.
=> Remove Rainbow, avoid race in creating directories

src/sugar3/graphics/alert.py, src/sugar3/graphics/icon.py, src/sugar3/graphics/palettewindow.py, src/sugar3/graphics/toolbarbox.py, src/sugar3/graphics/tray.py
Required by https://github.com/sugarlabs/sugar-artwork/pull/86
In Gtk+ 3.20, you need to use the css name to select elements,
rather than the gtype name.  Therefore, these must be added.
The css name must be set before the class instances are created, as
it effects the class rather than the instance.  This is why it must
be places after the class definition.
=> Set css name for widgets

src/sugar3/graphics/alert.py
For long messages and titles buttons were shifted out of the window!
Reported bug [#4945](https://bugs.sugarlabs.org/ticket/4945).
Refer to PR in sugar [#658](https://github.com/sugarlabs/sugar/pull/658)
=> Ellipsis in title and msg of alert

src/sugar3/graphics/icon.py, src/sugar3/test/uitree.py
Gi has been emitting warnings into the log to do this for some
time now. Not doing this has also caused bugs, such as #4900.
Also see https://github.com/sugarlabs/sugar/pull/600
=> Specify library version prior to import, fixes #4900

src/sugar3/graphics/palettewindow.py
The log is always filled with many of these errors where division by zero takes place especially when I drag objects from the clipboard to other places.
This is happening since the palette_dim.width is becoming 0 at times, so its rising the division by zero error.
=> Set value of "ph" to 0 if division by zero takes place

bin/sugar-activity, src/sugar3/activity/activity.py, src/sugar3/datastore/datastore.py, src/sugar3/graphics/style.py, src/sugar3/graphics/xocolor.py, src/sugar3/presence/buddy.py, src/sugar3/profile.py
- Handle lack of GSettings gracefully.
- Still requires sugar-datastore.
- Supports avoiding X11 docks/panels.
- Provides icons for Activity windows.
Try it outside Sugar. Go to an Activity directory and run 'sugar-activity'.
Tested it with Terminal, Finance, Write, Browse, Memorize under XFCE4.
Tested in Gnome under OLPC-OS.
Also works from Sugar Terminal Activity.
Does not affect regular Sugar operation.
=> Allow to run activities without Sugar shell.

bin/sugar-activity
The issue was caused by importing from activityfactory which caused GObject to be imported. This conflicts with GTK2. (Reported and original patch by James Cameron)
We should create the sugar profile's activity root if it doesn't exist yet, when running outside Sugar. But activity factory can't be used, because of this incompatibility.
=> Fix regression for GTK2 activities caused by 2f2b2d2

src/sugar3/activity/bundlebuilder.py
(cat.gettext can return None, which doesn't have a find method)
=> Ignore empty translated summary

src/sugar3/graphics/Makefile.am, src/sugar3/graphics/popwindow.py
@samdroid-apps , as discussed I have designed the pop-up model here.
Use of this can be seen in my PR in sugar repo.
Link-> https://github.com/sugarlabs/sugar/pull/672
=> Added new popwindow module in sugar3.graphics

src/sugar3/activity/activity.py
To test:
```
$ broadwayd :5 &
$ BROADWAY_DISPLAY=:5 GDK_BACKEND=broadway SESSION_MANAGER= sugar-activity <Activity Directory or nothing if already in one>
```
Then visit http://localhost:8085/
=> Allow running GTK3 Sugar Activities in HTML5

src/sugar3/graphics/palettewindow.py
Currently, the ToolInvoker code passes the button child in such a
way that the WidgetInvoker queues only the child's draw.  In previous
Gtk+ versions, this magically resulted in redrawing the parent as well.
However, Gtk+ 3.20 is probably trying to save power and not randomly
redraw widgets.  To fix this, we must queue the redraw of the widget
that we want to redraw explicitly.
https://bugs.sugarlabs.org/ticket/4960
=> Fix palette damage for tool buttons, fixes #4960

src/sugar3/presence/presenceservice.py
If the user has a "random" telepathy connection manager
installed and running on the system (eg. telepathy idle being
active if they are chatting on irc with GNOME's Polari), activities
will crash on startup.
Steps to reproduce the crash:
1. Run Polari (eg. via the Terminal activity)
2. Join an irc channel in Polari (eg. #sugar on freenode)
3. Try to open an activity from the home view
- notice that opening any sugar3 activity will crash
This is probably very relevant to @icarito GNOME patches, as many GNOME users probably have telepathy or empathy with "random" connection managers.  Steps to reproduce under gnome:
1.  Run Polarai, connected to #sugar on freenode
2.  `cd browse-activity`
3.  `sugar-activity`
-> ```Traceback (most recent call last):
File "/usr/bin/sugar-activity", line …
```
=> Don't assume all connection managers support Sugar

src/sugar3/activity/bundlebuilder.py
Extends the fix of #296
Git submodules are only listed by their root directory in the
output of "git ls-files".  Therefore, we must handle this case
so that the files from the module are included in the install
and dist_xo commands.
To reproduce the issue, you could do something like the following:
cd pippy
git clone https://github.com/samdroid-apps/collabwrapper
git add collabwrapper
python setup.py install  # or just osbuild run
=> Handle git submodules in bundlebuilder

src/sugar3/activity/activity.py
Gtk 3.20 recently changed the default setting so that buttons hide
their icons.  This is regression in terms of the Sugar HIG.
Same as https://github.com/sugarlabs/sugar/pull/694, but for activities (not the shell)
=> Show icons in buttons

src/sugar3/graphics/icon.py, src/sugar3/graphics/palettewindow.py
2 fixes for touch palette invocation on the home screen (with the favorite activity icons).  See commit descriptions for steps.
=> Touch Palette invocation fixes

src/sugar3/graphics/palettewindow.py
Problem 1, buddy menu palette appears on Sugar startup on physical hardware, or when mouse is centre of display.  The user did not command this.  It forces the user to dismiss the menu.
Problem 2, activity toolbars steal keyboard focus, when mouse is left in home view search box at activity start time.  The user did not command this.  It forces the user to dismiss the palette, or move the mouse to a safe place during activity start.
These palette invocations are caused by `enter-notify-event`s arriving when invokers are created under the cursor.  Fix is to ignore the event if the cursor has not moved.
=> Fix for uncommanded focus-stealing palettes

src/sugar3/graphics/palette.py, src/sugar3/graphics/palettewindow.py
Previously there was the concept of having 2 popdowns for a palette.
The first popdown showed the of tooltip the palette, and the 2nd
showed the content of the palette.  However, this was confusing
to new users, and made users wait for little reason.
This commit removes the 2nd popdown.  An example of this is when you
mouse over an icon to invoke the palette.  Previously, it showed
the tooltip, then made you wait, then showed the content of the
palette.  With this patch, the whole palette is shown at the
first popdown, making a snappy UX.
See https://www.sam.today/blog/sugar-with-instant-palettes/ for more background
Mailing list reference:  http://lists.sugarlabs.org/archive/sugar-devel/2016-May/052808.html
=> Unify palette popdowns

po/POTFILES.in
Was missing from a803876fbffaa5b36897a2d4dbeceb35d5b671de.
OLPC note: has been sent to manufacturing of SKU400.
=> Add missing popwindow to POTFILES.in

src/sugar3/bundle/activitybundle.py
ActivityBundle was making reference to _path private in Bundle, change
to use get_path public method.
OLPC note: has been sent to manufacturing of SKU400.
=> Avoid private member access to Bundle

src/sugar3/graphics/window.py
The unversioned import results in the following log noise:
/usr/lib/python2.7/site-packages/sugar3/graphics/window.py:26: PyGIWarning: GdkX11 was imported without specifying a version first. Use gi.require_version('GdkX11', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import GdkX11
See @davelab6's ticket at https://bugs.sugarlabs.org/ticket/4965
=> Version the GdkX11 import, fixes #4965

src/sugar3/activity/activity.py
Makes Sugar Activities more standard.
Companion of https://github.com/sugarlabs/sugar-toolkit/pull/5
=> Assign icon to window regardless of environment.

src/sugar3/graphics/animator.py
* Add do_stop method for animation
This adds a explicit method for cleaning up the animation.  Previously,
animations expected the next_frame to be called where frame=end.
That guarantee was never provided by the api.  This resulted in
animations sometimes being in odd states.  For example, Browse activity
had an animation that overrode the Gtk "draw" signal.  If the signal
was not unbound, the animated object was mistakenly rendered after
the completion of the animation, obstructing the user's view.
This api is explicit and allows cleaner code in the animation
implementation.  The clean up code goes in do_stop rather than in a
conditional of next_frame.
* Fix typos in sugar3.graphics.animator docs
=> Animator do_stop api

src/sugar3/graphics/palette.py
The popdown state argument was removed in 90cec5b, as the palette
popdowns were unified.  However, this is a public api.  Removing
the argument caused exceptions to be raised, breaking applications.
Most uses of the state argument were for the SECONDARY state, which
is now the default behaviour.
This commit re-adds the argument with a deprecation notice.
=> Proper deprecation of Palette.popdown state argument

src/sugar3/activity/activity.py, src/sugar3/graphics/palettewindow.py
Activity logs have continued to report GObject Introspection version warnings.
=> Further gi.require_version calls

examples/toolbutton.py, src/sugar3/graphics/radiotoolbutton.py, src/sugar3/graphics/toolbutton.py
Competing pull request replaces #345, #346, #347, and #348, derived from work by @Hrishi1999 and others.
----
Write documentation for sugar3.graphics.ToolButton
- add two examples,
- document critical properties as keyword arguments in the class init,
- ensure documentation is consistent between RadioToolButton and ToolButton, (as some of the text is similar),
- part of feature [Sugar3 Docs](https://wiki.sugarlabs.org/go/Features/Sugar3_Docs),
- follow [How To Guide](https://wiki.sugarlabs.org/go/Features/Sugar3_Docs/How_To_Write).
Derived from work by
- @Hrishi1999 Hrishi <hrishipatel99@gmail.com> (31176ea) and
- @ndefilippis radicalonion <ndefilippis98@gmail.com> (db89aca).
=> Write documentation for sugar3.graphics.ToolButton

src/sugar3/activity/bundlebuilder.py
Sort translation files when generating the .desktop file to output
reproducible results.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848633
Reviewed-by: James Cameron <quozl@laptop.org>
=> Sort translation files

examples/alert.py, examples/animator.py, examples/buttons.py, examples/colorbutton.py, examples/combobox.py, examples/common.py, examples/customdestroy.py, examples/gtktreesensitive.py, examples/iconbadges.py, examples/iconcache.py, examples/iconentry.py, examples/iconwidget.py, examples/notebook.py, examples/progress.py, examples/progressicon.py, examples/radiopalette.py, examples/radiotoolbutton.py, examples/scrollingdetector.py, examples/tabs.py, examples/ticket2855.py, examples/ticket3000.py, examples/toggletoolbutton.py, examples/toolbar.py, examples/toolbarpalettes.py, examples/toolbutton.py, examples/toolbuttons.py, examples/tray.py
- replaced Gtk.HBox/Gtk.VBox by GtkBox as seen in [1] and [2]
GtkHbox and GtkVBox are deprecated
- use delete-event instead of destroy event in GtkWindow
- replaced icon_size for pixel_size where used
it's also deprecated as seen in commit [3]
- use sugar_theme in all examples; set it manually not by just
importing common module
- fixed GtkBox.pack_start arguments
- flake/pep8 fixes
[1] https://developer.gnome.org/gtk3/stable/GtkHBox.html
[2] https://developer.gnome.org/gtk3/stable/GtkVBox.html
[3] 5802d67ee107ef82963770257071a779c4741a21
=> Example fixes

bin/sugar-activity
When an activity is launched, an import should first search the activity bundle source rather than `/usr/bin`.
Fixes the need to change activity sources every time a system package conflicts with an import.
May impact any activity that relies on a system package being in search path before the bundle source.  Forty activities were tested, and none relied on this.
See also https://github.com/sugarlabs/Pippy/pull/45
CC @icarito.
=> Prepend instead of append to path

examples/alert.py, src/sugar3/graphics/alert.py
**Effect of this PR:**
- `_TimeoutAlert` returns a response ID of -1 on timeout
- Checked for activities using this response via [this](https://github.com/search?q=org%3Asugarlabs+TimeoutAlert&type=Code). Turns out none of the activities use the response emitted on timeout.
@quozl Kindly review
=> Fix: #366 sugar3.graphics.alert.TimeoutAlert does not expose timeout condition 

src/sugar3/activity/widgets.py
**Fixed in this PR:** #375 
**Note:** This is an in progress PR
**Tested on:**
Sugar 0.112, Ubuntu 16.04
@quozl Kindly review
=> [Fix]: #375 (sugar3.activity.widgets.TitleEntry ignores enter key)

src/sugar3/graphics/icon.py
When an icon file name matches a GNOME theme icon;
```
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/sugar3/graphics/icon.py", line 214, in _get_attach_points
cp.readfp(config_file)
File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
self._read(fp, filename)
File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
```
Caused by reading a .png file as if it were config file, in turn because the icon was expected by the toolkit to be .svg file type.
Regression introduced by f796638.
Fixes https://github.com/sugarlabs/activity-abacus/issues/16
=> Fix traceback when an icon name matches a GNOME theme icon

src/sugar3/bundle/__init__.py
With reference to https://github.com/sugarlabs/activity-abacus/pull/17, new parameters are needed to be defined in activity metadata [activity.info] as other activities have been using them in reference to activity.info of [turtleart-activity](https://github.com/sugarlabs/turtleart-activity/blob/master/activity/activity.info) and others. 
This is important for displaying correct and accurate information of the activity on the web portal. 
The new parameters being:-    
1. category/categories 
2. website 
The description has also been updated for the same. All suggestions and edits are appreciated. 
- With respect to this, the example has also been updated of the `browse` activity that is listed below. 
- I have also taken the liberty to improve the description of already defined …
=> Define new parameters for activity metadata

.gitignore, src/sugar3/activity/activityinstance.py
Ensure environment variables needed by Python activities are available in each of the three supported scenarios;
- started from Sugar,
- started from Terminal inside Sugar,
- started by other desktop environments.
Variables always available are;
```
SUGAR_ACTIVITY_ROOT
SUGAR_BUNDLE_ID
SUGAR_BUNDLE_NAME
SUGAR_BUNDLE_PATH
SUGAR_BUNDLE_VERSION
```
Variables also available when started from Sugar are;
```
SUGAR_ACTIVITIES_HIDDEN
SUGAR_APISOCKET_KEY
SUGAR_APISOCKET_PORT
SUGAR_GROUP_LABELS
SUGAR_HOME
SUGAR_MIME_DEFAULTS
SUGAR_PROFILE
SUGAR_SCALING
SUGAR_VERSION
```
Variables also available when started from Terminal are;
```
SUGAR_TERMINAL_VERSION
```
Other changes;
- use os.makedirs in place of distutils.dir_util.mkpath,
- avoid redundant setting of SUGAR_BUNDLE_PATH,
- do not set …
=> Clean up activity environment variables

configure.ac
`configure` and `autogen.sh` now accept `--with-python2` or `--with-python3` options, with the default of python 2.
aa8a5e7 introduced building for python 3, but broke build for python 2, requiring patching `configure.ac` prior to build.
Code was derived from rpmfusion-packager, found using a GitHub search of `configure.ac` files for both `python2` and `python3`, and is GPLv3.
Tested on Ubuntu 18.04.
Signed-off-by: James Cameron <quozl@laptop.org>
@Aniket21mathur, please test.
=> Build for either python 2 or python 3

src/sugar3/activity/activity.py
Defer `iconify` call to after the activity has been shown.  Remember the `iconify` call was requested, and make the call just prior to entering the main loop.
On Ubuntu 18.04 with Metacity 3.32.0 the Journal does appear over the Home View on Sugar start on a VM with two virtual CPUs, yet the previous fix in Metacity (074af8f) is present.  This is suggestive of a race condition.
Tests with a minimal GTK reproducer shows order of three specific calls is critical to success of iconify.  The ordering and results are;
* `iconify`, `maximize`, `show`; not iconified,
* `maximize`, `iconify`, `show`; not iconified,
* `iconify`, `show`, `maximize`; not iconified,
* `maximize`, `show`, `iconify`; app with focus will flicker, iconified,
* `show`, `maximize`, `iconify`; app with focus may flicker, …
=> Defer Gtk.Window.iconify

src/sugar3/graphics/colorbutton.py, src/sugar3/graphics/iconentry.py, src/sugar3/graphics/tray.py
GLib accepts signal names with dash or underscore and
documents the signals with a dash.
Use of signal names in Sugar was mixed, change to using
dash only.
No functional change.
=> Dash in signal names

src/sugar3/graphics/objectchooser.py
Preview metadata in 0.114 and earlier was returned by datastore client as a dbus.ByteArray.
Regression introduced by aa8a5e7 ("Port from Python 2 to six").
```log
Traceback (most recent call last):
File "/usr/lib/python3.7/dist-packages/jarabe/journal/expandedentry.py", line 378, in _create_preview
pixbuf = get_preview_pixbuf(metadata.get('preview', ''))
File "/usr/lib/python3.7/dist-packages/sugar3/graphics/objectchooser.py", line 85, in get_preview_pixbuf
preview_data = base64.b64decode(preview_data)
File "/usr/lib/python3.7/base64.py", line 87, in b64decode
return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (237) cannot be 1 more than a multiple of 4
```
Related to
https://github.com/sugarlabs/sugar-datastore/issues/16
Requires …
=> Port to Python 3 - preview metadata is bytes

src/sugar3/speech.py
The schema is provided by the sugar shell package and in scenarios where that package is not present trying to reference ends up in segfaults, e.g. flatpak apps.
=> speech: Check if speech schema is present

src/sugar3/graphics/colorbutton.py
ColorButton did not show button icon, and swatches were too small
making it almost unusable. Color chooser toolbar had been using
Gtk.IconSize.LARGE_TOOLBAR which return 0 as size.
style.GRID_CELL_SIZE was used as size reference
@quozl @walterbender @Hrishi1999 @Aniket21mathur
=> Fix icon size in ColorButton [GCI]

configure.ac
5fa33b2 introduced build for either python 2 or python 3, with the
default of python 2.
`configure` and `autogen.sh` now accept `--with-python3` or
`--with-python2` options, with the default of python 3.
Signed-off-by: James Cameron <quozl@laptop.org>
=> Build by default for python 3

src/sugar3/activity/bundlebuilder.py
If no arguments are passed, parser.parse_args() returns
command = None
Traceback:
```
$ python2 ./setup.py
usage: ./setup.py [-h]
{install,check,dist_xo,dist_source,build,fix_manifest,genpot,dev}
...
./setup.py: error: too few arguments
$ python3 ./setup.py
Traceback (most recent call last):
File "./setup.py", line 5, in <module>
bundlebuilder.start()
File "/usr/lib/python3.7/dist-packages/sugar3/activity/bundlebuilder.py", line 637, in start
globals()['cmd_' + options.command](config, options)
TypeError: can only concatenate str (not "NoneType") to str
```
=> Fix bundlebuilder not handling empty arguments

src/sugar3/activity/bundlebuilder.py
* simplify messages,
* add desktop and appdata files to messages,
* add DESTDIR support.
=> Add setup.py --destdir support

.github/workflows/docs.yml, ci/docs.sh
```
ci: install sphinx
ci: deploy to sugar3 subdirectory
ci: add deploy/.nojekyll
ci: first make sugar-toolkit-gtk3 before docs
ci: enable deb-src repositories
ci: add gir1.2-sugarext-1.0 and remove sugar build
```
* Merge this pull request after reviewing the difference between https://developer.sugarlabs.org/sugar3 and https://dev.sl.srevinsaju.me/sugar3
* Ping me on IRC :smile:
=> ci: automatically deploy documentation to gh-pages

src/sugar3/activity/bundlebuilder.py
File names are quoted and then mishandled by the builder.
http://lists.sugarlabs.org/archive/sugar-devel/2021-February/058971.html
Use null-terminated files.
Untested.
=> Fix ls-files quoting

ci/docs.sh
The index.html page was supposed to be placed in the deploy folder which would
then be staged and deployed to github actions.
=> ci: change path of placing the index.html for developer.sugarlabs.org

.github/workflows/docs.yml, ci/docs.sh
sphinxcontrib.napolean is not provided any more by the default
sphink package, so we will need to manually add them
=> ci: add sphinxcontrib.napoleon for parsing sugar docs

src/sugar3/eggsmclient-xsmp.c
This avoids an implicit function declaration and build failures with future compilers.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
=> Include <gdk/gdkx.h> for a declaration of gdk_x11_set_sm_client_id

src/sugar3/presence/buddy.py
Fixes #443 
Buddy.props.key is supposed to be a str, but is stored as a dbus.ByteArray before being sent to dbus, decoding it after the call to GetProperties fixes the issue of it being bytes.
Activities like maze that use Buddy.props.key needed to encode the received key before comparison worked.
@quozl kindly review.
Tested without `key = str(key.encode())` in maze activity and collaboration works as expected.
=> Fix issue with Buddy.props.key being bytes

src/sugar3/activity/widgets.py
After setting the text cursor colour in sugar-artwork, make it visible in the toolkit.
Related to https://github.com/sugarlabs/sugar-artwork/pull/119
@quozl kindly review.
Fixes #377.
=> Make cursor in textview visible

src/sugar3/bundle/activitybundle.py, src/sugar3/bundle/contentbundle.py, src/sugar3/graphics/icon.py
- This Pull Request addresses the deprecation of the readfp method in the configparser module. The readfp method has been replaced with the read_file method to ensure compatibility with newer versions of Python.
- Fixes #477
Replaced readfp with read_file in all instances.
=> Fix deprecated readfp method of configparser
