sugarlabs/sugar-toolkit-gtk3

src/sugar3/graphics/toolbarbox.py

Add gtype name to ToolbarBox for gtk css styling

---

src/sugar3/graphics/alert.py

- s/Set/Get for a get property method,
- fix two typos.

fix alerts documentation

---

src/sugar3/graphics/alert.py

Create a private class for the button, timeout and response.  Use the private class as parent for both ```NotifyAlert``` and ```TimeoutAlert```.
Extends the spurious response fix (cfeabdc) to ```NotifyAlert```.
Also use ```g_timeout_add``` in preference to ```g_timeout_add_seconds```, because the latter is less precise in implementation.  See https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add-seconds
Tested by changing the Register alert temporarily.
Replaces https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/264

move guts of TimeoutAlert and NotifyAlert to a private class

---

src/sugar3/graphics/window.py

Write documentation for the sugar3.graphics.window module

Write documentation for sugar3.graphics.window

---

src/sugar3/graphics/palettewindow.py

A rework of the TreeViewInvoker used by the journal and activity list.
Fixes a persistent journal entry palette that reappears in journal or home view.  See [#4918](https://bugs.sugarlabs.org/ticket/4918).
Also fixes an over-sensitive journal icon; with the journal mostly empty, rapidly move the mouse from the bottom of the screen into the lowest icon and then out again.  Before this patch, the palette was shown.  After this patch, the mouse must rest in the icon.
Changes made:
- expose _ensure_palette_exists in Invoker and rename to force_palette, so it can be used in TreeViewInvoker,
- remove reference to MouseSpeedDetector, it is no longer required,
- remove enter and leave events; they are for the TreeView as a whole, and are not required,
- properly detect that None is returned by …

Fix persistent tree view palettes

---

src/sugar3/graphics/objectchooser.py

Add docs and improve previously present docstrings in sugar3.graphics.objectchooser module.

Add and improve docs for sugar3.graphics.objectchooser

---

src/sugar3/presence/activity.py

CHANNEL_TYPE_TUBES was deprecated since telepathy-gabble 0.17.25 and
is no longer present on modern distributions. This breaks collaboration
for _all_ activities, regardless if they use tubes or not.
Therefore, check if the channel creation failed due to support and allow
channel creation process to continue.
This patch fixes collaboration for the activities that do not use tubes
channel in modern distributions, but also allow to use tubes when running
on older distributions.
Signed-off-by: Martin Abente Lahaye <tch@sugarlabs.org>

collaboration: handle tubes channel failure gracefully

---

make-doc.sh

Changing interpreter to /bin/sh from /usr/bin/sh so it will work with ubuntu

Change make-doc.sh interpreter

---

src/sugar3/graphics/style.py

I made a new branch, and this one should have correct indentation

Write docs for sugar3.graphics.style

---

src/sugar3/graphics/animator.py

Replaces #213 - rebased and few changes to improve reliability
Gtk 3.8 introduces the tick callback [1]. This allows widgets to be
signaled before each frame, simmilar to requestAnimationFrame in the
browser.
This patch adds an optional widget argument to the Animator class so
tick based animation can be used. This is much more efficent than
using timeouts, as we get a more appropriate frame rate for the user.
[1] https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-add-tick-callback

Add a widget parameter to the Animator (tick based animations)

---

src/sugar3/activity/bundlebuilder.py

Do you want to review this @icarito?
This will allow .desktops for all of the activities to be
packaged.  In the future, we could ship a special launcher script
so that the user can choose the jobject to run, but for now
we just open the activity using the command specified in the
activity.info file.
To test, just `./osbuild shell`, `build` and then `python setup.py install` an activity.  You will need to copy the desktop file, something like:
cp ~/sugar-build/build/out/sandbox/install/share/applications/org.laptop.WebActivity.activity.desktop  /usr/local/share/applications/
Alternatively, don't use osbuild and don't do the extra copy!
------
*Using the issue tracker as a mailing list*
I'm really excited about making all the `.desktop` entries, because it will let us use AppStream!  I was …

Generate .desktop files for activities during install

---

examples/iconbadges.py
src/sugar3/graphics/icon.py

@walterbender, so I took your idea of improving the docs and got all excited.  I wrote this and then got very bored and left it on my latptop.  Anyway, I have finally made the commit for this one, and I would appreciate if you could review/merge.

First pass sugar3.graphics.icon docs

---

src/sugar3/activity/bundlebuilder.py
src/sugar3/bundle/activitybundle.py

Probably replaces https://github.com/hughsie/appstream-glib/pull/111

Bundlebuilder patches, including generating AppStream data files!

---

bin/sugar-activity

(Quite an old change found in OLPC branch but not yet upstream.)

sugar-activity: typo

---

examples/toggletoolbutton.py
src/sugar3/graphics/toggletoolbutton.py

Rebased #352 because there were unexpected changes.

Documentation for ToggleToolButton

---

examples/progressicon.py
src/sugar3/graphics/progressicon.py

I have added docs and example for progressicon. 
Earlier PRs:
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/354
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/299
Review it.

Added documentation and example for progressicon

---

examples/alert.py
examples/animator.py
examples/combobox.py
examples/common.py
examples/customdestroy.py
examples/gtktreesensitive.py
examples/iconcache.py
examples/iconentry.py
examples/notebook.py
examples/radiopalette.py
examples/radiotoolbutton.py
examples/scrollingdetector.py
examples/toolbar.py
examples/toolbutton.py

doesn't affect that much the code, it just remove
unused modules and make it look better.

fixed the flake8 errors for examples

---

examples/colorbutton.py
src/sugar3/graphics/colorbutton.py

The example is tested and it works, though I have a doubt. If I test this example in PEP8, it will give warning about there is no last line at the end of file but if I use flake8, it gives me warning about and empty last line at end of file. 
Please review it.
Update : I have squashed multiple commits.

Added example and documentation for colorbutton

---

src/sugar3/activity/bundlebuilder.py

Similar to custom mime types, allow to disable it.

Allow to disable installing .desktop files

---

po/LINGUAS
po/ach.po
po/da.po
po/hr.po
po/pt_BR.po

Update LINGUAS and some PO files

2017 06 03 translations

---

src/sugar3/datastore/datastore.py

This pull request _will_ incorporate changes needed/observed while working on [Datastore/#8](https://github.com/sugarlabs/sugar-datastore/pull/8)

fix datastore status signal name usage

---

src/sugar3/profile.py

Fixes fix 39b7e606 handle new OpenSSH DSA key format.

get_profile() - Use tuple instead of list.

---

src/sugar3/presence/activity.py
src/sugar3/presence/buddy.py

Port to Python 3 via Six aa8a5e7 did introduce a regression during activity collaboration on both sharing and joining.
Fixes https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/406

Fix collaboration call_async

---

src/sugar3/activity/activity.py
src/sugar3/presence/activity.py
src/sugar3/presence/buddy.py
src/sugar3/presence/connectionmanager.py
src/sugar3/presence/presenceservice.py
src/sugar3/presence/sugartubeconn.py

Continued from #401 (In progress pr) 
@quozl @pro-panda . Can you please test it.Thanks.

Port to TelepathyGLib

---

src/sugar3/activity/activity.py
src/sugar3/datastore/datastore.py
src/sugar3/dispatch/dispatcher.py
src/sugar3/dispatch/saferef.py
src/sugar3/util.py

@quozl @pro-panda please review.

Port to six fixes

---

src/sugar3/speech.py

Fix NameError introduced by 23e664df05

---

src/sugar3/activity/activity.py
src/sugar3/profile.py

Fixes https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/434

Fixe Python3.8 SyntaxWarnings 

---

src/sugar3/activity/bundlebuilder.py

Fixes #440, @quozl kindly review.

Add --from-code parameter to xgettext for a python3 activity

---

src/sugar3/eggsmclient.c
src/sugar3/event-controller/sugar-event-controller.c
src/sugar3/event-controller/sugar-event-controller.h
src/sugar3/event-controller/sugar-long-press-controller.c
src/sugar3/event-controller/sugar-long-press-controller.h
src/sugar3/event-controller/sugar-rotate-controller.c
src/sugar3/event-controller/sugar-rotate-controller.h
src/sugar3/event-controller/sugar-swipe-controller.c
src/sugar3/event-controller/sugar-swipe-controller.h
src/sugar3/event-controller/sugar-touch-controller.c
src/sugar3/event-controller/sugar-touch-controller.h
src/sugar3/event-controller/sugar-zoom-controller.c
src/sugar3/event-controller/sugar-zoom-controller.h
src/sugar3/sugar-cursor-tracker.c
src/sugar3/sugar-cursor-tracker.h
src/sugar3/sugar-gesture-grabber.c
src/sugar3/sugar-gesture-grabber.h

Fixes #405
@quozl @aperezbios kindly review.

Fix deprecations

---

configure.ac
src/sugar3/activity/webactivity.py

Port to WebKit2 4.1
